// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvyoyatygljyudljxdfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2eW95YXR5Z2xqeXVkbGp4ZGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTg0MDUsImV4cCI6MjA2MTc5NDQwNX0.c_GCNenYuHVB7w7R8E8dm8OrUZJvoMcTNNoMDwuyIbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);